matrix:
  include:
    - language: python
      python: 2.7
      services:
        - docker
      install:
        - docker images
      script:
        - docker build -t app .
    - language: ruby
      addons:
        code_climate:
          repo_token: fda6f4f9bf2387705b47cd6135429a29a11ae9c5927afe01a18ee3e33c47246a
        apt:
          packages:
            - libqtwebkit-dev
            - libqtwebkit4
      before_install:
        - gem install bundler
      before_script:
        - cp config/application.travis.yml config/application.yml
        - cp config/database.travis.yml config/database.yml
        - psql -c 'create database fablabs_test' -U postgres
        - npm install
        - bundle config git.allow_insecure true
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      env:
        global:
          - secure: MlhI/NpTblhwPavClDAl87CxpPrgys3/EbmMLTQnq9zHBc8YbpnCeQ92eMs6NAMdh64090BOcbxSgph4aAKqdd5QoX7VU07sduEaaIkSaFQ26jN4rrc2iS6dHRFIGND6mZ2hmvrmw5zGvMYLTdP7vaTyjNzCDIZCmtOxcLJ4jCk=
        matrix:
          - DB=postgresql
      cache: bundler
      script:
        - bundle exec rake db:schema:load
        - bundle exec rake db:test:prepare
        - bundle exec rake
          #- bundle exec codeclimate-test-reporter
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
      services:
        - redis-server
        - postgresql
      sudo: false
      deploy:
        - provider: script
          skip_cleanup: true
          script: "./.travis-deploy.sh"
          on:
            branch: master
