version: '2.2'

services:
  redis:
    image: redis:latest
    hostname: redis
    restart: always

  # service configuration for Postgres
  db:
    # use the preferred version of the official Postgres image
    # see https://hub.docker.com/_/postgres/
    image: postgres
    restart: always
    hostname: db1
    # persist the database between containers by storing it in a volume
    volumes:
      - fablabs-postgres:/var/lib/postgresql/data
      - ./dump:/dump
    environment:
      - DB_NAME="fablabs"
      - DB_USER="postgres"
      - DB_PASSWORD=""

  # service configuration for our dockerized Rails app
  app:
    env_file: .env
    # use the Dockerfile next to this file
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/fablabs
      - /fablabs/tmp
    depends_on:
      - db
      - redis
      - memcached
    # expose the port we configured Puma to bind to (should expose only internally)
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - AWS_BUCKET=${AWS_BUCKET}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET=${AWS_SECRET}
      - EMAIL_AUTHENTICATION=${EMAIL_AUTHENTICATION}
      - EMAIL_ADDRESS=${EMAIL_ADDRESS}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_DOMAIN=${EMAIL_DOMAIN}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - S3_BUCKET=${S3_BUCKET}
      #- DEV_DB_USERNAME="postgres"
      #- DEV_DB_PASSWORD="${DEV_DB_PASSWORD}"
      - DEV_DB_HOST=db
      - DB_NAME=fablabs
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - MEMCACHED_HOST=memcached://memcached:11211/
      - OPBEAT_ORG_ID=${OPBEAT_ORG_ID}
      - OPBEAT_APP_ID=${OPBEAT_APP_ID}
      - OPBEAT_SECRET=${OPBEAT_SECRET}
      - SECRET_TOKEN=${SECRET_TOKEN}
      - REDIS_URL=redis://redis:6379/12
      - GEONAMES_USERNAME=${GEONAMES_USERNAME}
    ports:
      - "3000:3000"
    restart: always
    #command: rails s

  worker:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /fablabs/tmp
    volumes_from:
      - app
    command: bash -c "sleep 3 && bundle exec sidekiq -e $RAILS_ENV"
    restart: always
    depends_on:
      - app
      - db

  # service configuration for our web server
  web:
    env_file: .env
    image: steveltn/https-portal
    depends_on:
      - app
    environment:
      DOMAINS: "${MY_DOMAIN}"
      STAGE: "${MY_STAGE}" #local or production
    restart: always
    # expose the port we configured Nginx to bind to (it is ok to expose externally)
    ports:
      - 80:80
      - 443:443

  memcached:
    image: memcached:1.5.3
    restart: always
    ports:
      - "11211:11211"

volumes:
  fablabs-postgres:
