development: &defaults
  adapter      : postgresql
  encoding     : unicode
  database     : fablabs_develop
  pool         : 20
  min_messages : WARNING

  username : <%= ENV['DEV_DB_USERNAME'] %>
  password : <%= ENV['DEV_DB_PASSWORD'] %>
  host     : <%= ENV['DEV_DB_HOST'] %>

test:
  <<: *defaults
  database     : <%= ENV['TEST_DB_NAME']  || 'fablabs_testdb' %>

production:
  <<: *defaults
  database : <%= ENV['DB_NAME'] %>
  username : <%= ENV['DB_USERNAME'] %>
  password : <%= ENV['DB_PASSWORD'] %>
  host     : <%= ENV['DB_HOST'] %>
